apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-python-app
  namespace: stage  # Use the "stage" namespace for this deployment
spec:
  replicas: 2 # Number of pods to run
  selector:
    matchLabels:
      app: my-python-app
  template:
    metadata:
      labels:
        app: my-python-app
    spec:
      containers:
        - name: my-python-app
          image: siddmi0407/my-python-app:v2  # Use the image we pushed
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "256Mi"  # Minimum memory request
              cpu: "250m"      # Minimum CPU request (250 milli-CPU units)
            limits:
              memory: "512Mi"  # Maximum memory limit
              cpu: "500m"      # Maximum CPU limit (500 milli-CPU units)
