apiVersion: v1
kind: Service
metadata:
  name: my-python-app
  namespace: production  # Use the "production" namespace for the service
spec:
  selector:
    app: my-python-app
  ports:
    - protocol: TCP
      port: 80          # Port to expose the service
      targetPort: 8080  # Container's port
      nodePort: 30081   # Port to expose on the node
  type: NodePort  # Change type to NodePort
