name: Deploy to Kubernetes

on:
  push:
    branches:
      - 'master'  # Trigger the workflow on pushes to the master branch
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Build and push the Docker image
      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME="siddmi0407/my-python-app:latest"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      # Set up kubectl
      - name: Set up Kubernetes Configuration
        run: |
          mkdir -p ~/.minikube/profiles/minikube
          mkdir -p ~/.kube
          
          echo "${{ secrets.KUBE_CLIENT_CERT }}" | base64 --decode | tee ~/.minikube/profiles/minikube/client.crt > /dev/null
          echo "${{ secrets.KUBE_CLIENT_KEY }}" | base64 --decode | tee ~/.minikube/profiles/minikube/client.key > /dev/null
          echo "${{ secrets.KUBE_CA_CERT }}" | base64 --decode | tee ~/.minikube/ca.crt > /dev/null
          echo "${{ secrets.KUBECONFIG_BASE64 }}" | base64 --decode | tee ~/.kube/config > /dev/null
          
          sed -i 's|https://192.168.49.2:8443|https://c82c-2405-201-303c-4069-d0e-4273-d4cb-3377.ngrok-free.app|g' ~/.kube/config
          
          chmod 600 ~/.minikube/profiles/minikube/*
          chmod 600 ~/.kube/config
          
          chown -R $USER ~/.minikube ~/.kube
      
      - name: Test Kubernetes Connection
        run: | 
          kubectl get nodes

      # Deploy to Kubernetes (Stage)
      - name: Deploy to Stage Namespace
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml

      # Deploy to Kubernetes (Production)
      - name: Deploy to Production Namespace
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          kubectl config set-context --current --namespace=production
          kubectl apply -f deployment-prod.yaml
          kubectl apply -f service-prod.yaml
